# Generated by Django 3.2.23 on 2024-01-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0008_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='time_annotated',
            field=models.IntegerField(default=0),
        ),
    ]
