# Generated by Django 3.2.23 on 2024-01-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0009_example_time_annotated'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='confidence',
            field=models.BooleanField(default=True),
        ),
    ]
