# Generated by Django 3.2.23 on 2024-01-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0010_example_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='changed',
            field=models.BooleanField(default=False),
        ),
    ]
